### ISSUE TITLE
Create simplified version of HTTP Endpoint with Read Content and Type hidden

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1269]
This is continuation of discussion from #1249.
I'm reopening this as an issue since my gut feeling is that some code changes will be required.
If I am wrong, feel free to close this and send me a bill for a beer or two :).....

My use case is that I want to have a HTTP Endpoint like activity which has only Path visible and Read Content, Method and Type should be hidden and set to some value I need.

Per our discussion I did this code to have activity inheriting endpoint, with Read Content, Method and Type properties set to default values I need and hidden from UI.

    public class CustomizeTestReceiveRequest : INotificationHandler<DescribingActivityType>
    {
        // hiding some properties from UI
        public Task Handle(DescribingActivityType notification, CancellationToken cancellationToken)
        {
            var descriptor = notification.ActivityDescriptor;
            if (descriptor.Type == typeof(TestReceiveRequest).Name)
            {
                descriptor.InputProperties = descriptor.InputProperties.Where(x => x.Name != "ReadContent" && x.Name != "TargetType" && x.Name != "Methods").ToArray();
            }
            return Task.CompletedTask;
        }
    }

    [Trigger(
        Category = "Test",
        DisplayName = "Receive Request",
        Description = "Wait for an test request.",
        Outcomes = new[] { OutcomeNames.Done }
    )]
    public class TestReceiveRequest : HttpEndpoint
    {
        // here to specify default value
        [ActivityInput(DefaultValue = true)]
        public new bool ReadContent { 
            get; 
            set; 
        } = true;

        // here to specify default value
        [ActivityInput(DefaultValue = typeof(string))]
        public new Type? TargetType { get; set; } = typeof(string);
    }

    public class TestReceiveRequestBookmarkkProvider : BookmarkProvider<HttpEndpointBookmark, TestReceiveRequest>
    {
        public override async ValueTask<IEnumerable<BookmarkResult>> GetBookmarksAsync(BookmarkProviderContext<TestReceiveRequest> context, CancellationToken cancellationToken)
        {
            var path = ToLower(await context.ReadActivityPropertyAsync<HttpEndpoint, PathString>(x => x.Path, cancellationToken))!;
            var methods = new[] { "post" };

            BookmarkResult CreateBookmark(string method) => Result(new(path, method), nameof(HttpEndpoint));
            return methods.Select(CreateBookmark);
        }

        private static string ToLower(string? s) => s?.ToLowerInvariant();
    }

However it does not work. UI display is correct but when activated it behaves as if `ReadContent` is `false` and `TargetType` is `emtpy/null`, I always get `HTTPRequestModel` with Body set to `null`.

It seems that `HTTPEndpointMiddleware` is ignoring my default values in code :(.
Probably this two lines:

            var activityWrapper = workflowBlueprintWrapper.GetUnfilteredActivity<HttpEndpoint>(pendingWorkflow.ActivityId!);
            var readContent = await activityWrapper!.EvaluatePropertyValueAsync(x => x.ReadContent, cancellationToken);

I've placed breakpoint on `ReadContent` setter and getter both in my code and in original Elsa code and they get invoked way after `HTTPEndpointMiddleware` is executing (when the workflow is running). 
I've even tried making `ReadContent` virtual in Elsa code and override in mine, but that did not change anything.

It seems to me `HTTPEndpointMiddleware` is ignoring default values and code in this case :(.....

I've traced `EvaluatePropertyValueAsync` in `HTTPEndpointMiddleware` to the `WorkflowBlueprintExtensions` `GetActivityPropertyValue` method which only seems to get the values that are visible in UI/Bluprint and does not that into account default values.

Unfortunately my attempts to make it take default values into account have failed :(.
Can you please advise how to make my needed use case work?

Thanks.

**Comment by sfmskywalker** [comment]
I think you're right. The property evaluator ignores the default value, but I think it makes sense that it should fall back to it when reading a property value from an activity. I will fix.

**Comment by sfmskywalker** [comment]
While fixing that default value thing, I realized that removing the properties as you're doing per my suggestion further complicates things - because after all, when you remove a property, you're also  removing the default value with it 😄

So looks like we'll be needing some additional metadata after all to control whether or not properties should be "browsable" or not.

**Comment by sfmskywalker** [comment]
I pushed two changes:

1. Read default value when there's either no value provider or when the value is null.
2. IsBrowsable metadata for activity properties, allowing you to control property visibility.

Use it like this:

```csharp
public class CustomizeTestReceiveRequest : INotificationHandler<DescribingActivityType>
{
    // hiding some properties from UI
    public Task Handle(DescribingActivityType notification, CancellationToken cancellationToken)
    {
        var descriptor = notification.ActivityDescriptor;
        
        if (descriptor.Type != nameof(TestReceiveRequest)) 
            return Task.CompletedTask;
        
        var hiddenProperties = descriptor.InputProperties.Where(x => x.Name == "ReadContent" && x.Name == "TargetType" && x.Name == "Methods");

        foreach (var hiddenProperty in hiddenProperties) 
            hiddenProperty.IsBrowsable = false;
        
        return Task.CompletedTask;
    }
}
```

Notice that I'm setting `IsBrowsable` to false, which will prevent the server API to return any of these properties to the designer.
But the default values you provide will still be read.

**Comment by tomy2105** [comment]
I've tried hiding via `IsBrowseable`.
UI looks OK but it still doesn't work for me (behaves as ReadContent is false, etc.....).....

My whole fork for testing can be found at: https://github.com/tomy2105/elsa-core/tree/test/HTTPEndpointExtension
It includes:
- my test activity and bookmark and handler at: https://github.com/tomy2105/elsa-core/blob/test/HTTPEndpointExtension/src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/TestReceiveRequest.cs
- registration of bookmark and notification handler at: https://github.com/tomy2105/elsa-core/blob/test/HTTPEndpointExtension/src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/Startup.cs
- export of test workflow at: https://github.com/tomy2105/elsa-core/blob/test/HTTPEndpointExtension/src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/workflow-definition-custom-http-endpoint.json

As you can see in workflow export there are not other property besides endpoint path string :(. Maybe this indicates source of problem, don't know if defaulted ones should be here?

**Comment by sfmskywalker** [comment]
I cloned your fork, created a workflow with your test endpoint activity, posted a request, and checked for the `ReadContent` setting in the middleware with debugger attached:

![image](https://user-images.githubusercontent.com/938393/126707400-ca715bfa-3329-412c-9bb7-8cc1f0834907.png)

In other words, I can't seem to reproduce the issue.

The workflow export only shows activity properties that are also present on the designer, and does not cause any issues with default values of hidden properties from what I have seen.

Perhaps you can try again? If you are still seeing this issue, then please provide me with detailed repro steps.

**Comment by tomy2105** [comment]
Now you got me puzzled :(...

I did the same.
Deleted my fork entirely from my computer, cloned again, npm builded from scratch, compiled solution from scratch and got **opposite** result :(.

Tested with following curl command:
curl "https://localhost:15265/workflows/mytest54321" -H "Content-Type: application/json" --data-raw "{""foo"":""bar""}"


![VSReadContent](https://user-images.githubusercontent.com/7658839/126799395-1946af90-cc27-4df8-9a82-1683b5998b5e.png)

`readContent` was false and curl got response without body:

![Curl](https://user-images.githubusercontent.com/7658839/126799396-1915dcbd-d168-4d5a-8416-e0df0e9c406a.png)

What could be the reason for this? Any advice?
How did you post data? Used curl or something else?
Could you try with my curl command?

**Comment by sfmskywalker** [comment]
I used Postman, but the method of invoking the HTTP request is irrelevant, because the `readContent` value is received from the default value of your custom activity.

What you could try is clone the Elsa repo (not your fork) and see if you can reproduce it again with your custom activity.
If you can, then let me know and I will follow the same steps (ideally, you delete all bin and obj folders and zip the source code and send it over to me).

**Comment by sfmskywalker** [comment]
Closing this for now since I can't seem to reproduce the issue, but please reopen if you have a repro for me to look at. Thank you.
