### ISSUE TITLE
System.NullReferenceException when Using  Rebus Activity ReceiveMessage in Designer 

### ISSUE THREAD

**Issue by sebguischr** [elsa-workflows/elsa-core#1326]
When using Rebus Activity ReceiveMessage in Designer, I get this error when publishing the WorkFlow:

```
Rebus.Retry.ErrorTracking.InMemErrorTracker : Unhandled exception 1 while handling message with ID "5881251a-873f-4036-a797-674cf8003ff9"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Activities.Rebus.Bookmarks.MessageReceivedTriggerProvider.GetBookmarksAsync(BookmarkProviderContext`1 context, CancellationToken cancellationToken)
   at Elsa.Services.Bookmarks.BookmarkProvider`2.Elsa.Services.Bookmarks.IBookmarkProvider.GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForBookmarkProvider(IBookmarkProvider provider, BookmarkProviderContext context, IActivityBlueprint activityBlueprint, IWorkflowBlueprint workflowBlueprint, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider.GetTriggersForActivityBlueprintAsync(IActivityBlueprint activityBlueprint, WorkflowExecutionContext workflowExecutionContext, IDictionary`2 activityTypes, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggersForBlueprintsProvider.<>c__DisplayClass6_0.<<GetWorkflowTriggersForWorkflowBlueprintAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetWorkflowTriggersForWorkflowBlueprintAsync(IWorkflowBlueprint workflowBlueprint, IDictionary`2 activityTypes, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggersForBlueprintsProvider.GetTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(IEnumerable`1 workflowBlueprints, CancellationToken cancellationToken)
   at Elsa.Services.Triggers.TriggerIndexer.IndexTriggersAsync(CancellationToken cancellationToken)
   at Rebus.Pipeline.Receive.HandlerInvoker`1.Invoke()
   at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)
```

It seems that the MessageType wrote in the editor is not saved and return null.

**Comment by sfmskywalker** [comment]
It looks like this issue has been resolved over time since I cannot reproduce. Please feel free to reopen the issue if you can provide a repro with the latest prerelease (2.3 from MyGet). Thanks!

**Comment by sebguischr** [comment]
I tried again with the latest prerelease and still get the same error.
Here is my sample app : https://github.com/sebguischr/ElsaRebus that I just upgraded to 2.3 preview.

**Comment by sfmskywalker** [comment]
@sebguillot Thanks for the link. At first sight, your projects are still referencing 2.1.1.463. Maybe you need to push your recent changes?

**Comment by sebguischr** [comment]
Ok, I pushed it.

**Comment by sfmskywalker** [comment]
Looking at your .csproj file, I noticed a couple of issues:

![image](https://user-images.githubusercontent.com/938393/134161558-860d1291-c118-4e28-a418-10745cb57207.png)

1. The DLL reference needs to be removed.
2. All Elsa package references need to be of the same version. Don't use mixed versions.

Once you updated that, try again and let me know if you are still having the issue you reported. If so, push your changes and I will take a look.

**Comment by sebguischr** [comment]
I updated correctly I think all the references but, unfortunately, still get the same error. I pushed the changes.

**Comment by sfmskywalker** [comment]
Fix pushed and will be available from MyGet after the current build finishes (don't take the RC1 from NuGet, which is older).

**Comment by sebguischr** [comment]
Thanks a lot!
