### ISSUE TITLE
SQLite Error 1: 'no such column: w.Scope'

### ISSUE THREAD

**Issue by Va55ago** [elsa-workflows/elsa-core#432]
I just tried to create a sample Blazor Server app simply running the Elsa Dashboard (to evaluate Elsa). Following the guide, I imported the Elsa, Elsa.Dashboard and Elsa.Persistence.EntityFrameworkCore packages at the latest version (1.4.1) and added the following to the startup.cs file
```csharp
services
    .AddElsa(elsa =>
        elsa.AddEntityFrameworkStores<SqliteContext>(configureOptions =>
            configureOptions.UseSqlite(@"Data Source=C:\Temp\Data\elsa.db;Cache=Shared;")))
    .AddElsaDashboard()
    .AddConsoleActivities()
    .AddHttpActivities();
```

I then added a SqliteContextFactory (to set the connection string as above) and deployed the database using `dotnet ef database update`. However, when running the application, I get the following error:
`SqliteException: SQLite Error 1: 'no such column: w.Scope'.`

This error disappears if I downgrade the Elsa.Persistence.EntityFramework nuget package to 1.4.0.

Repro project and full stack trace below:

[Elsa.Blazor.Server.zip](https://github.com/elsa-workflows/elsa-core/files/5445267/Elsa.Blazor.Server.zip)

```
SqliteException: SQLite Error 1: 'no such column: w.Scope'.

    Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(int rc, sqlite3 db)
    Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
    Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
    Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
    Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
    Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
    Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
    Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+AsyncEnumerator.InitializeReaderAsync(DbContext _, bool result, CancellationToken cancellationToken)
    Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+AsyncEnumerator.MoveNextAsync()
    Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken)
    Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken)
    Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowInstanceStore.ListByBlockingActivityAsync(string activityType, string correlationId, CancellationToken cancellationToken)
    Elsa.Extensions.WorkflowInstanceStoreExtensions.ListByBlockingActivityAsync<TActivity>(IWorkflowInstanceStore store, string correlationId, CancellationToken cancellationToken)
    Elsa.Activities.Http.RequestHandlers.Handlers.TriggerRequestHandler.HandleRequestAsync()
    Elsa.Activities.Http.Middleware.RequestHandlerMiddleware<THandler>.InvokeAsync(HttpContext httpContext, THandler handler)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by sfmskywalker** [comment]
This issue was introduced recently. It broke the YesSql provider as well which was fixed, but EF Core hasn't been updated yet. Thank you for reporting we'll get this fixed.

**Comment by sfmskywalker** [comment]
I just pushed a fix and will be available on NuGet shortly as 1.4.2.

**Comment by Va55ago** [comment]
Thanks for the quick update.

Unfortunately, after updating all the Elsa packages to 1.4.3, I ran the database migration again and I got the following error:
`SQLite does not support this migration operation ('DropColumnOperation'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.`

I downgraded Elsa.Persistence.EntityFrameworkCore to version 1.4 and ran the app again. Then, even more unfortunately, I found that when I clicked on "Workflows" menu item in the dashboard, I got the following error:
`System.MissingMethodException: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.`

My guess would be that the failed migration corrupted the database in some way.

In my case, this isn't too big an issue. I can easily just delete the database and recreate my test workflow from scratch. However, I thought you'd want to know in case other people have this same issue.

Full stack traces and a copy of my "corrupted" database are below:

Hope that helps

**Initial Database Migration Error**
```
Applying migration '20201027192013_Update02'.
System.NotSupportedException: SQLite does not support this migration operation ('DropColumnOperation'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.
   at Microsoft.EntityFrameworkCore.Migrations.SqliteMigrationsSqlGenerator.Generate(DropColumnOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_12(MigrationsSqlGenerator g, MigrationOpera      at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_12(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_12(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqliteMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
SQLite does not support this migration operation ('DropColumnOperation'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.
```

**Corrupted Database Issue**
```
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Object -> IEnumerable`1
System.Object -> System.Collections.Generic.IEnumerable`1[[Elsa.Models.WorkflowInstance, Elsa.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
 ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
WorkflowInstanceEntity -> WorkflowInstance
Elsa.Persistence.EntityFrameworkCore.Entities.WorkflowInstanceEntity -> Elsa.Models.WorkflowInstance

Type Map configuration:
WorkflowInstanceEntity -> WorkflowInstance
Elsa.Persistence.EntityFrameworkCore.Entities.WorkflowInstanceEntity -> Elsa.Models.WorkflowInstance

Destination Member:
Activities

 ---> System.MissingMethodException: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.
   at Elsa.Persistence.EntityFrameworkCore.Mapping.ActivityInstanceEntityCollectionConverter.<>c__DisplayClass0_0.<Convert>b__1(ActivityInstanceEntity x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Elsa.Persistence.EntityFrameworkCore.Mapping.ActivityInstanceEntityCollectionConverter.Convert(ICollection`1 sourceMember, ResolutionContext context)
   at lambda_method(Closure , Object , IEnumerable`1 , ResolutionContext )
   --- End of inner exception stack trace ---

   at lambda_method(Closure , Object , IEnumerable`1 , ResolutionContext )
   --- End of inner exception stack trace ---

   at lambda_method(Closure , Object , IEnumerable`1 , ResolutionContext )
   at Elsa.Services.AutoMapperMapper.Map[TDestination](Object source)
   at Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowInstanceStore.Map(IEnumerable`1 source)
   at Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowInstanceStore.ListByDefinitionAsync(String definitionId, CancellationToken cancellationToken)
   at Elsa.Extensions.AsyncEnumerableExtensions.ToListAsync[T](Task`1 task)
   at Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowDefinitionController.CreateWorkflowDefinitionListItemModelAsync(WorkflowDefinitionVersion workflowDefinition, CancellationToken cancellationToken)
   at Elsa.Dashboard.Areas.Elsa.Controllers.WorkflowDefinitionController.Index(CancellationToken cancellationToken)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Elsa.Activities.Http.Middleware.RequestHandlerMiddleware`1.InvokeAsync(HttpContext httpContext, THandler handler)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Corrupted Database**
[elsa.zip](https://github.com/elsa-workflows/elsa-core/files/5452964/elsa.zip)

**Comment by Va55ago** [comment]
Actually, I've just found that even deleting the database file, I still get the database migration error about being unable to drop a column when using Elsa.Persistence.EntityFrameworkCore 1.4.3.

I'll have to roll back to 1.4.0 and recreate the database to continue my evaluation.

**Comment by sfmskywalker** [comment]
As it turns out, Sqlite doesn't support dropping columns. Instead, the entire table must be dropped and then recreated. I'm disappointed that EF Core actually goes through each migration step even for new databases. I would have expected it to be smart enough to create the database in its final state immediately.

I'll regenerate the Sqlite migration such that it creates the database in its final state (no creating and dropping columns).

I apologize for the inconvenience this breaking change introduced.
