### ISSUE TITLE
[BUG]3.2.0 RC2 Instance view, step into executed workflow activities no longer possible

### ISSUE THREAD

**Issue by JochenSteinbrenner** [elsa-workflows/elsa-core#5730]
## Description
Good morning.
Workflow instance view. After update from RC1 to RC2 it is no longer possible to step into executed workflow instances by double-clicking on them. The child workflow is not opened. in the following example, double-click on ScaleDischarge-Classic does no longer open the execution of ScaleDischarge-Classic
![Debug](https://github.com/elsa-workflows/elsa-core/assets/38906531/403fd03e-278f-4779-be2e-5977de70fab4)

## Steps to Reproduce
- Create child workflow
- Check Usable as activity
- Call child within parent workflow as activity
- Execute parent
- Open instances and double click on child activity

## Expected Behavior
Execution of child workflow shown in instance view

## Environment
- 3.2.0 RC2 in backend
- Elsa Studio as docker container: elsaworkflows/elsa-studio-v3:sha-0816443

Regards Jochen Steinbrenner

**Comment by JochenSteinbrenner** [comment]
Browser development console shows `ActivityDoubleClick`, but no errors

**Comment by sfmskywalker** [comment]
Does this happen on existing workflow instances only, or also on new workflow instances?

**Comment by JochenSteinbrenner** [comment]
It happens with new workflow instances, too...

**Comment by sfmskywalker** [comment]
I can't seem to reproduce this behavior. Is there any chance you could share a sample project that demonstrates this symptom?

**Comment by sfmskywalker** [comment]
Never mind, I skipped the mention of using the Docker images - can reproduce it with the Studio+Server image, too. Will fix.

**Comment by JochenSteinbrenner** [comment]
Perfect, thank you!

**Comment by sfmskywalker** [comment]
It's fixed with the new v3.2.0-rc3 images that is built from the `patch/3.2.x branch`. I tested it using the following command`:

```shell
docker pull elsaworkflows/elsa-server-and-studio-v3-2-0-rc3:latest
docker run -t -i -e ASPNETCORE_ENVIRONMENT='Development' -e HTTP_PORTS=8080 -e HTTP__BASEURL=http://localhost:13000 -p 13000:8080 elsaworkflows/elsa-server-and-studio-v3-2-0-rc3:latest
```

The Elsa Studio Docker container for 3.2 is named: `elsaworkflows/elsa-studio-v3-2-0-rc3`.

The `main` branch still needs to be updated, which means that `elsaworkflows/elsa-studio-v3` isn't fixed until then.

**Comment by JochenSteinbrenner** [comment]
Hello, I'm sorry. 
But with latest docker container of ELSA Studio elsaworkflows/elsa-studio-v3:sha-0816443
and ELSA 3.2 RC3 in backend, it does not work. Executions of child workflows still not shown in instance view.
Double-click on workflow activity does not open the workflow execution...

Can you please take a quick look at this issue?

Thank you very much.
Regards Jochen Steinbrenner

**Comment by sfmskywalker** [comment]
No worries, please make sure to use the new image name: `elsaworkflows/elsa-studio-v3-2-0-rc3` instead of `elsaworkflows/elsa-studio-v3`. It should work, but let me know if not. Thank you.
